config/routes.rb
Rails.application.routes.draw do
  

  
  devise_for :views
  devise_for :users
  resources :users
  resources :religions
 # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :ayats
  root to: 'pages#home'
  get '/library' => 'pages#library'
  get '/about' => 'pages#about'
  get '/search_page' => 'pages#search_page'

  resources :books
  	get 'books/id/read' => 'books#read'
  
  resources :surahs
  get '/search' => 'search#index'
  #resources :search, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/surah.rb
class Surah < ApplicationRecord
	belongs_to :book
	has_many :ayats, dependent: :destroy 
	
end

app/controllers/surahs_controller.rb
class SurahsController < ApplicationController
  before_action :set_surah, only: [:show, :edit, :update, :destroy]

  # GET /surahs
  # GET /surahs.json
  def index
    @surahs = Surah.all.order("surah_number ASC")
  end

  # GET /surahs/1
  # GET /surahs/1.json
  def show
  end

  # GET /surahs/new
  def new
    @surah = Surah.new
  end

  # GET /surahs/1/edit
  def edit
  end

  # POST /surahs
  # POST /surahs.json
  def create
    @surah = Surah.new(surah_params)

    respond_to do |format|
      if @surah.save
        format.html { redirect_to @surah, notice: 'Surah was successfully created.' }
        format.json { render :show, status: :created, location: @surah }
      else
        format.html { render :new }
        format.json { render json: @surah.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surahs/1
  # PATCH/PUT /surahs/1.json
  def update
    respond_to do |format|
      if @surah.update(surah_params)
        format.html { redirect_to @surah, notice: 'Surah was successfully updated.' }
        format.json { render :show, status: :ok, location: @surah }
      else
        format.html { render :edit }
        format.json { render json: @surah.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surahs/1
  # DELETE /surahs/1.json
  def destroy
    @surah.destroy
    respond_to do |format|
      format.html { redirect_to surahs_url, notice: 'Surah was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surah
      @surah = Surah.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def surah_params
      params.require(:surah).permit(:book_id, :surah_number, :surah_name)
    end
end

app/helpers/surahs_helper.rb
module SurahsHelper
end

app/views/surahs/_form.html.erb
<%= form_for(surah) do |f| %>
  <% if surah.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(surah.errors.count, "error") %> prohibited this surah from being saved:</h2>

      <ul>
      <% surah.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %>
    
     <%= collection_select(:surah, :book_id, Book.all, :id, :name,:prompt => true) %>
  
  </div>


  <div class="field">
    
       <%= f.label :surah_number %>
    <%= f.number_field :surah_number %>
  </div>

  <div class="field">
    <%= f.label :surah_name %>
    <%= f.text_field :surah_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surahs/_newform.html.erb
<%= form_for(surah) do |f| %>
  <% if surah.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(surah.errors.count, "error") %> prohibited this surah from being saved:</h2>

      <ul>
      <% surah.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
rhis
  <div class="field">
    <%= f.label :book_id %>
       
     <%= collection_select(:surah, :book_id, Book.all, :id, :name,:prompt => true) %>
  
  </div>


  <div class="field">
    
       <%= f.label :surah_number %>
    <%= f.number_field :surah_number %>
  </div>

  <div class="field">
    <%= f.label :surah_name %>
    <%= f.text_field :surah_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



app/views/surahs/edit.html.erb
<h1>Editing Surah</h1>

<%= render 'form', surah: @surah %>

<%= link_to 'Show', @surah %> |
<%= link_to 'Back', surahs_path %>

app/views/surahs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surahs/verses</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Surah/chapter number</th>
      <th>Surah/chapter name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surahs.each do |surah| %>
      <tr>
         <td><%= Book.find(surah.book_id).name %></td>
        <td><%= surah.surah_number %></td>
        <td><%= surah.surah_name %></td>
        <td><%= link_to 'Show', surah %></td>
        <td><%= link_to 'Edit', edit_surah_path(surah) %></td>
        <td><%= link_to 'Destroy', surah, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Surah/Chapter', new_surah_path %>

app/views/surahs/new.html.erb
<h1>New Surah</h1>

<%= render 'newform', surah: @surah %>

<%= link_to 'Back', surahs_path %>

app/views/surahs/show.html.erb
 

<p align="center" id="notice"><%= notice %></p>

<p>
  
</p>


<body style="background-color: #b5f7bf">

<div class="sidenav">
    
   
	
	<%@book=Book.find(@surah.book_id)%>
    <% if @book.name=="The Holy Al Quran"%>
          <h2 align="center"><%= link_to "All Surah", Book.find(@surah.book_id) %></h2>
        <%else%>
          <h2 align="center"><%= link_to "All Chapter", Book.find(@surah.book_id) %></h2>
    <%end%>


    
    <% @book.surahs.each do |surah| %>
    <%= link_to surah.surah_name, surah%>
    <% end %>
</div>


        


<div class="main">
 	  <h1 align="center"><u><%= @surah.surah_name %></u></h1>
      <h2 align="center">Bismillahir Rahmanir Rahim</h2>
      	<%@surah.ayats.each do|ayate| %>
     	<p>(<%= ayate.ayat_number%>)-- <%= ayate.ayat_text%></p>
      <%end%>

</div align="right">
   <%= link_to 'Edit', edit_surah_path(@surah) %> |
	<%= link_to 'Back', surahs_path %>
</body>


<div style="text-align: right;">

 <%= form_for Ayat.new do |f| %>
      <div class="field">
        <%= f.label :book_id %>

        <%=f.hidden_field :book_id, value: Surah.find(params[:id]).book_id%>
        <%= Surah.find(params[:id]).book.name  %>
      </div>



      <div class="field">
        <%= f.label :surah_id %>
        <%=f.hidden_field :surah_id, value: params[:id]%>
        <%= Surah.find(params[:id]).surah_name  %>
         
      </div>

      <div class="field">
        <%= f.label :ayat_number %>
        <% if Surah.find(params[:id]).ayats.any?%>
        <%= f.number_field :ayat_number, value: Surah.find(params[:id]).ayats.last.ayat_number+1 %>
        <%else%>

        <%= f.number_field :ayat_number, value: 0+1 %>
        <%end%>

      </div>

      <div class="field">
        <%= f.label :ayat_text %>
        <%= f.text_area :ayat_text %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
<% end %>

</div>