config/routes.rb
Rails.application.routes.draw do
  

  
  devise_for :views
  devise_for :users
  resources :users
  resources :religions
 # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :ayats
  root to: 'pages#home'
  get '/library' => 'pages#library'
  get '/about' => 'pages#about'
  get '/search_page' => 'pages#search_page'

  resources :books
  	get 'books/id/read' => 'books#read'
  
  resources :surahs
  get '/search' => 'search#index'
  #resources :search, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/religion.rb
class Religion < ApplicationRecord
	has_many :books, dependent: :destroy
end

app/controllers/religions_controller.rb
class ReligionsController < ApplicationController
  before_action :set_religion, only: [:show, :edit, :update, :destroy]

  # GET /religions
  # GET /religions.json
  def index
    @religions = Religion.all
  end

  # GET /religions/1
  # GET /religions/1.json
  def show
  end

  # GET /religions/new
  def new
    @religion = Religion.new
  end

  # GET /religions/1/edit
  def edit
  end

  # POST /religions
  # POST /religions.json
  def create
    @religion = Religion.new(religion_params)

    respond_to do |format|
      if @religion.save
        format.html { redirect_to @religion, notice: 'Religion was successfully created.' }
        format.json { render :show, status: :created, location: @religion }
      else
        format.html { render :new }
        format.json { render json: @religion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /religions/1
  # PATCH/PUT /religions/1.json
  def update
    respond_to do |format|
      if @religion.update(religion_params)
        format.html { redirect_to @religion, notice: 'Religion was successfully updated.' }
        format.json { render :show, status: :ok, location: @religion }
      else
        format.html { render :edit }
        format.json { render json: @religion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /religions/1
  # DELETE /religions/1.json
  def destroy
    @religion.destroy
    respond_to do |format|
      format.html { redirect_to religions_url, notice: 'Religion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_religion
      @religion = Religion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def religion_params
      params.require(:religion).permit(:name)
    end
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/views/religions/_form.html.erb
<%= form_for(religion) do |f| %>
  <% if religion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(religion.errors.count, "error") %> prohibited this religion from being saved:</h2>

      <ul>
      <% religion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/religions/edit.html.erb
<h1>Editing Religion</h1>

<%= render 'form', religion: @religion %>

<%= link_to 'Show', @religion %> |
<%= link_to 'Back', religions_path %>

app/views/religions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Religions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @religions.each do |religion| %>
      <tr>
        <td><%= religion.name %></td>
        <td><%= link_to 'Show', religion %></td>
        <td><%= link_to 'Edit', edit_religion_path(religion) %></td>
        <td><%= link_to 'Destroy', religion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Religion', new_religion_path %>

app/views/religions/new.html.erb
<h1>New Religion</h1>

<%= render 'form', religion: @religion %>

<%= link_to 'Back', religions_path %>

app/views/religions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @religion.name %>
</p>

<%= link_to 'Edit', edit_religion_path(@religion) %> |
<%= link_to 'Back', religions_path %>