config/routes.rb
Rails.application.routes.draw do
  

  
  devise_for :views
  devise_for :users
  resources :users
  resources :religions
 # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :ayats
  root to: 'pages#home'
  get '/library' => 'pages#library'
  get '/about' => 'pages#about'
  get '/search_page' => 'pages#search_page'

  resources :books
  	get 'books/id/read' => 'books#read'
  
  resources :surahs
  get '/search' => 'search#index'
  #resources :search, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ayat.rb
class Ayat < ApplicationRecord
	belongs_to :surah
	belongs_to :book

 include PgSearch

 pg_search_scope :search, against: [:ayat_text]
  
end

app/controllers/ayats_controller.rb
class AyatsController < ApplicationController
  before_action :set_ayat, only: [:show, :edit, :update, :destroy]

  # GET /ayats
  # GET /ayats.json
  def index
    @ayats = Ayat.all.order("ayat_number ASC")
    
  end

  # GET /ayats/1
  # GET /ayats/1.json
  def show
  end

  # GET /ayats/new
  def new
    @ayat = Ayat.new
    def populate_surah_list
      book_id = params[:book_id]
      @surah = Surah.find_by book_id: book_id
      respond_to do |format|
        format.json { render json: @surah }
      end
    end

  end

  # GET /ayats/1/edit
  def edit
  end

  # POST /ayats
  # POST /ayats.json
  def create
    @ayat = Ayat.new(ayat_params)

    respond_to do |format|
      if @ayat.save
        format.html { redirect_to @ayat, notice: 'Ayat was successfully created.' }
        format.json { render :show, status: :created, location: @ayat }
      else
        format.html { render :new }
        format.json { render json: @ayat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ayats/1
  # PATCH/PUT /ayats/1.json
  def update
    respond_to do |format|
      if @ayat.update(ayat_params)
        format.html { redirect_to @ayat, notice: 'Ayat was successfully updated.' }
        format.json { render :show, status: :ok, location: @ayat }
      else
        format.html { render :edit }
        format.json { render json: @ayat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayats/1
  # DELETE /ayats/1.json
  def destroy
    @ayat.destroy
    respond_to do |format|
      format.html { redirect_to ayats_url, notice: 'Ayat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ayat
      @ayat = Ayat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ayat_params
          
      params.require(:ayat).permit(:book_id, :surah_id, :ayat_number, :ayat_text)
   
    end
end

app/helpers/ayats_helper.rb
module AyatsHelper
end

app/views/ayats/_form.html.erb
<%= form_for(ayat) do |f| %>
  <% if ayat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ayat.errors.count, "error") %> prohibited this ayat from being saved:</h2>

      <ul>
      <% ayat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id, id: "book" %>
    <%= collection_select(:ayat, :book_id, Book.all, :id, :name) %>
  </div>



  <div class="field">
    <%= f.label :surah_id %>
     <%= collection_select(:ayat, :surah_id, Surah.all, :id, :surah_name) %>
     
  </div>

  <div class="field">
    <%= f.label :ayat_number %>
    <%= f.number_field :ayat_number %>

  </div>

  <div class="field">
    <%= f.label :ayat_text %>
    <%= f.text_area :ayat_text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




<script type="text/javascript">
  $(document).ready(function() {
  $("#book").on('change', function(){
    $ajax({
      url: "populate_surah_list",
      type: "GET",
      data: {book_id: $(this).val()},
      // Callbacks that will be explained
    })
  });


  // Ajax call
success: function(data) {
  $("#surah_id").children().remove();
  // Create options and append to the list
}
// Rest of Ajax call
</script>

app/views/ayats/edit.html.erb
<h1>Editing Ayat</h1>

<%= render 'form', ayat: @ayat %>

<%= link_to 'Show', @ayat %> |
<%= link_to 'Back', ayats_path %>

app/views/ayats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ayats</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Book</th>
      <th>Surah</th>
      <th>Ayat number</th>
      <th>Ayat Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ayats.each do |ayat| %>
      <tr>
        <td><%= ayat.book_id %></td>
        <td><%= ayat.surah_id %></td>
        <td><%= ayat.ayat_number %></td>
        <td><%= ayat.ayat_text %></td>
        <td><%= link_to 'Show', ayat %></td>
        <td><%= link_to 'Edit', edit_ayat_path(ayat) %></td>
        <td><%= link_to 'Destroy', ayat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ayat', new_ayat_path %>

app/views/ayats/new.html.erb
<h1>New Ayat</h1>

<%= render 'form', ayat: @ayat %>

<%= link_to 'Back', ayats_path %>

app/views/ayats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @ayat.book_id %>
</p>

<p>
  <strong>Surah:</strong>
  <%= @ayat.surah_id %>
</p>

<p>
  <strong>Ayat number:</strong>
  <%= @ayat.ayat_number %>
</p>

<p>
  <strong>Ayat:</strong>
  <%= @ayat.ayat_text %>
</p>

<%= link_to 'Edit', edit_ayat_path(@ayat) %> |
<%= link_to 'Back', ayats_path %>